### ISSUE TITLE
Some display problems

### ISSUE THREAD

**Issue by KHLFYY** [CrSjimo/junze#1]
The "days" on the page don't show up on the iPhone's Safari. Some Unicode characters are non-Chinese characters.

**Comment by KHLFYY** [comment]
额 既然能打中文就不用生草机了
junze经历了两个月的玉米集训，又回到家乡H市了
所以不重新计数吗？

**Comment by CrSjimo** [comment]
Due to the fact that I does not has a Macintosh to debug the website on Safari, I cannot patch it aimed to Safari.

I am trying to discover what leads to this bug on mdn.

Sorry for the inconvenience.

________________________________
发件人: KHLFYY ***@***.***>
发送时间: 2021年7月15日星期四 21:12
收件人: CrSjimo/junze
抄送: Subscribed
主题: [CrSjimo/junze] Some display problems (#1)


The "days" on the page don't show up on the iPhone's Safari. Some Unicode characters are non-Chinese characters.

―

**Comment by CrSjimo** [comment]
已经修复了

________________________________
发件人: KHLFYY ***@***.***>
发送时间: 2021年7月17日星期六 22:27
收件人: CrSjimo/junze
抄送: Subscribed
主题: Re: [CrSjimo/junze] Some display problems (#1)


额 既然能打中文就不用生草机了
junze经历了两个月的玉米集训，又回到家乡H市了
所以不重新计数吗？

―

**Comment by KHLFYY** [comment]
好消息
自定义中的天数在Safari上显示正常
（但预设的俊泽和赵总的仍然显示NaN）

希望对修复bug有一定的帮助
